fixed assembler specs

diff --git a/bin/sisrs b/bin/sisrs
--- a/bin/sisrs
+++ b/bin/sisrs
@@ -76,7 +76,7 @@ MAINFOLDER=.
 THRESHOLD=1
 ALLELES=1
 DEBUG=0
-ASSEMBLER=Velvet
+ASSEMBLER=velvet
 OUTLENGTH=500000
 CMD=$1
 
@@ -112,22 +112,20 @@ DIRS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"    #where is the sisrs 
 DIR=$( dirname ${DIRS} )                                    #go one level up from location of sisrs file
 MAINFOLDER=$( echo "${MAINFOLDER}" | sed -e "s/\/*$//" )    #remove trailing / if necessary
 
-if [[ $ASSEMBLER == "Velvet" ]]; then
+if [[ $ASSEMBLER == "velvet" ]]; then
     which velveth &>/dev/null
-    [ $? -eq 0 ] || { echo "Velvet must be installed to run SISRS. The installation folder must be in your path.    Aborting."; exit 1; }
+    [ $? -eq 0 ] || { echo "Velvet must be installed to run SISRS. The installation folder must be in your path. Velvet is called as 'velveth' and 'velvetg'.    Aborting."; exit 1; }
     CONTIGS=velvetoutput
-fi
-
-if [[ $ASSEMBLER == "minia" ]]; then
+elif [[ $ASSEMBLER == "minia" ]]; then
     which minia &>/dev/null
-    [ $? -eq 0 ] || { echo "Minia must be installed to run SISRS. The installation folder must be in your path.    Aborting."; exit 1; }
+    [ $? -eq 0 ] || { echo "Minia must be installed to run SISRS. The installation folder must be in your path. Minia is called as 'minia'.    Aborting."; exit 1; }
     CONTIGS=miniaoutput
-fi
-
-if [[ $ASSEMBLER == "ABYSS" ]]; then
+elif [[ $ASSEMBLER == "abyss" ]]; then
     which ABYSS &>/dev/null
-    [ $? -eq 0 ] || { echo "ABYSS must be installed to run SISRS. The installation folder must be in your path.    Aborting."; exit 1; }
+    [ $? -eq 0 ] || { echo "Abyss must be installed to run SISRS. The installation folder must be in your path. Abyss is called as 'ABYSS'.    Aborting."; exit 1; }
     CONTIGS=abyssoutput
+else
+    echo "You must specify the assembler as velvet, minia, or abyss. If you do not specify an assembler SISRS will use velvet as the default.  Aborting."; exit 1;
 fi
 
 which bowtie2 &>/dev/null
@@ -176,7 +174,7 @@ subSample(){
 
 buildContigs(){
     rm -r ${MAINFOLDER}/${CONTIGS}
-    if [[ $ASSEMBLER == "Velvet" ]]; then
+    if [[ $ASSEMBLER == "velvet" ]]; then
         #make reference contigs - velveth
         if [ -n "${REFFILE}" ]; then
             if [[ ${#FILELISTU[@]} -gt 0 ]]; then
@@ -268,9 +266,9 @@ identifyFixedSites(){
 
 outputAlignment(){
     if [ -n "${REFFILE}" ]; then
-        ${DIR}/libexec/sisrs/get_alignment.py $((${#FOLDERLISTA[@]} - 2)) ${REFFILE} ${MAINFOLDER}
+        ${DIR}/libexec/sisrs/get_alignment.py $((${#FOLDERLISTA[@]} - 2)) ${REFFILE} ${MAINFOLDER} ${ASSEMBLER}
     else
-        ${DIR}/libexec/sisrs/get_alignment.py $((${#FOLDERLISTA[@]} - 2)) X ${MAINFOLDER}       #alignment with up to all but 2 missing
+        ${DIR}/libexec/sisrs/get_alignment.py $((${#FOLDERLISTA[@]} - 2)) X ${MAINFOLDER} ${ASSEMBLER}       #alignment with up to all but 2 missing
     fi
 }
 
