Added step to process alignment.nex and alignment_pi.nex in parallel for comparsion

diff --git a/bin/sisrs b/bin/sisrs
--- a/bin/sisrs
+++ b/bin/sisrs
@@ -423,13 +423,24 @@ outputAlignment(){
 }
 
 changeMissing(){
-    ${DIR}/libexec/sisrs/filter_nexus_for_missing.py ${OUTFOLDER}/alignment_pi.nex ${MISSING}       #alignment w specified number missing
+    ${DIR}/libexec/sisrs/filter_nexus_for_missing.py ${OUTFOLDER}/alignment_pi.nex ${MISSING}       #alignment w specified number missing from alignment_pi.nex
     if [[ $? != 0 ]]; then
         echo "filtering for missing failed"
         exit 1
     fi
     #Clean locs_m*.txt file
     tr " " "\n" < ${OUTFOLDER}/locs_m${MISSING}.txt | grep -oe "SISRS_[^/]*" - | uniq -c | sort -k1 -nr | awk '{print $2}' > "${OUTFOLDER}/locs_m${MISSING}_Clean.txt"
+
+    #Parallel processing of alignment.nex for comparison
+    mkdir ${OUTFOLDER}/alignmentDataWithSingletons
+    mv ${OUTFOLDER}/alignment.nex ${OUTFOLDER}/alignmentDataWithSingletons
+    ${DIR}/libexec/sisrs/filter_nexus_for_missing.py ${OUTFOLDER}/alignmentDataWithSingletons/alignment.nex ${MISSING}       #alignment w specified number missing from alignment.nex
+    if [[ $? != 0 ]]; then
+        echo "filtering for missing failed"
+        exit 1
+    fi
+    #Clean locs_m*.txt file
+    tr " " "\n" < ${OUTFOLDER}/alignmentDataWithSingletons/locs_m${MISSING}.txt | grep -oe "SISRS_[^/]*" - | uniq -c | sort -k1 -nr | awk '{print $2}' > "${OUTFOLDER}/alignmentDataWithSingletons/locs_m${MISSING}_Clean.txt"
 }
 
 runSISRS(){
