Commiting changes to sisrs shell file.
Former-commit-id: 56149ef86b7a8557ecc1dfbc1b01d9e6088be59d

diff --git a/bin/sisrs b/bin/sisrs
--- a/bin/sisrs
+++ b/bin/sisrs
@@ -27,6 +27,8 @@ By default, SISRS assumes that
     A minimum of three reads are required to call the base at a site for a taxon.
 
 Default settings can be changed using the following flags:
+    
+    sisrs [loci] ... -a [DIR] : will also extract the relevant alignments
 
     -g : use to specify the approximate genome size - this is optional but will reduce the size of the composite assembly by using a subset of reads to approximate 10x coverage
     -r : use to specify the location of the reference genome (must be a fasta file)
@@ -39,7 +41,8 @@ Default settings can be changed using the following flags:
     -t : use to specify the threshold for calling a site; e.g. 0.99 means that >99% of bases for that taxon must be one allele; only recommended for low ploidy with <3 individuals
     -s : use to specify the steps to skip: 1 skips making the composite genome; 2 also skips aligning reads to the composite reference; 3 also skips getting data for each site and mapping the composite genome to a known reference if available; 4 skips to identifying whether sites are variable among taxa given data for each site for each taxon
 
-    Example command: ./sisrs -g 50000000 -r ./reference.fasta -p 40 -f fastq -m 4 -a test_data"
+    Example command: ./sisrs -g 50000000 -r ./reference.fasta -p 40 -f fastq -m 4 -a test_data
+    Example command: ./sisrs loci -g 50000000 -r ./reference.fasta -p 40 -f fastq -m 4 -a test_data"
     }
 
 #use defaults or input values
@@ -53,30 +56,32 @@ REPEAT=0
 LOCI=0
 WITHIN=0
 ALLELES=1
+DEBUG=0
 
 if [[ $1 = "loci" ]]; then
     LOCI=1
     OPTIND=2 # tells getopts to start parsing at the second argument
 fi
 
-while getopts q:g:r:k:p:m:a:l:n:s:t:h option
+while getopts q:g:r:k:p:m:a:l:n:s:t:hd option
 do
-case "${option}"
-    in
-        q) REPEAT=${OPTARG};;
-        g) GENOMESIZE=${OPTARG};;
-        r) REFFILE=${OPTARG};;
-        k) KMER=${OPTARG};;
-        p) PROCESSORS=${OPTARG};;
-        m) MISSING=${OPTARG};;
-        a) MAINFOLDER=${OPTARG};;
-        l) ALLELES=${OPTARG};;
-        n) MINREAD=${OPTARG};;
-        t) THRESHOLD=${OPTARG};;
-        s) SKIP=${OPTARG};;
-        h) help; exit;;
-        \? ) echo "Unknown option" >&2; exit 1;;
-        esac
+    case "${option}"
+	in
+	q) REPEAT=${OPTARG};;
+	g) GENOMESIZE=${OPTARG};;
+	r) REFFILE=${OPTARG};;
+	k) KMER=${OPTARG};;
+	p) PROCESSORS=${OPTARG};;
+	m) MISSING=${OPTARG};;
+	a) MAINFOLDER=${OPTARG};;
+	l) ALLELES=${OPTARG};;
+	n) MINREAD=${OPTARG};;
+	t) THRESHOLD=${OPTARG};;
+	s) SKIP=${OPTARG};;
+	d) DEBUG=1;;
+	h) help; exit;;
+	\? ) echo "Unknown option" >&2; exit 1;;
+    esac
 done
 
 if [ -z $1 ]; then
@@ -332,6 +337,7 @@ function runGFR()
 	done  
 	mv "${MAINFOLDER}"/ref_genes.fasta "${MAINFOLDER}"/ref_genes.fa
     else
+	# TODO: Should this code be removed? 
 	for F in *.sam; do 
 	    python ${DIR}/libexec/gfr/make_alignment_from_sam.py ${F} ${ALLELES}; 
 	done
@@ -340,9 +346,12 @@ function runGFR()
 }
 
 if [[ ${LOCI} -eq 0 ]]; then
+    # Run SISRS only
     echo "**** SISRS ****"
-    #runSISRS
+    runSISRS
 else
+    # Run SISRS with loci (GFR). First check if alignment.nex and/or ref_genes.fa. If there is no alignment.nex then rerun SISRs to produce file. If
+    # ref_genes.fa doesn't exist then build it from alignment.nex
     echo "**** SISRS loci ****"
     if [ ! -f ${MAINFOLDER}/ref_genes.fa ] && [ ! -f "${MAINFOLDER}/alignment.nex" ]; then
 	# need to rerun SISRs from scratch to get ref_genes.fa
@@ -363,15 +372,16 @@ fi
     
 
 
-
-#echo "DIRS          = ${DIRS}"
-#echo "DIR           = ${DIR}"
-echo "MAINFOLDER    = ${MAINFOLDER}"
-#echo "FILELIST      = ${FILELIST[@]}"
-echo "FOLDERLIST    = ${FOLDERLIST[@]}"
-#echo "FILELISTA     = ${FILELISTA}"
-#echo "FILELISTU     = ${FILELISTU[@]}"
-#echo "FILELISTA[@]  = ${FILELISTA[@]}"
-#echo "#FILELISTU[@] = ${#FILELISTU[@]}"
-#echo "FOLDERLISTA   = ${FOLDERLISTA}"
-#echo "MISSING       = ${MISSING}"
+if [[ DEBUG -eq 1 ]]; then
+    echo "DIRS          = ${DIRS}"
+    echo "DIR           = ${DIR}"
+    echo "MAINFOLDER    = ${MAINFOLDER}"
+    echo "FILELIST      = ${FILELIST[@]}"
+    echo "FOLDERLIST    = ${FOLDERLIST[@]}"
+    echo "FILELISTA     = ${FILELISTA}"
+    echo "FILELISTU     = ${FILELISTU[@]}"
+    echo "FILELISTA[@]  = ${FILELISTA[@]}"
+    echo "#FILELISTU[@] = ${#FILELISTU[@]}"
+    echo "FOLDERLISTA   = ${FOLDERLISTA}"
+    echo "MISSING       = ${MISSING}"
+fi
