check assembler

diff --git a/bin/sisrs b/bin/sisrs
--- a/bin/sisrs
+++ b/bin/sisrs
@@ -30,16 +30,16 @@ Default settings can be changed using the following flags:
     
     sisrs [loci] ... -a [DIR] : will also extract the relevant alignments
 
-    -g : use to specify the approximate genome size - this is optional but will reduce the size of the composite assembly by using a subset of reads to approximate 10x coverage
+    -g : use to specify the approximate genome size - this will reduce the size of the composite assembly by using a subset of reads to approximate 10x coverage
     -r : use to specify the location of the reference genome (must be a fasta file)
     -k : use to specify k-mer size
     -p : use to specify the number of processors available
-    -f : use to specify reads in fasta format
     -l : use to specify the number of alleles for sisrs loci
-    -m : use to specify the number of species allowed to have missing data at a site
-    -a : use to specify the folder containing the folders of reads
+    -m : use to specify the number of species allowed to have missing data at a site (skipping this and filtering later is recommended)
+    -f : use to specify the folder containing the folders of reads
     -n : use to specify the number of reads required to call a base at a site
     -t : use to specify the threshold for calling a site; e.g. 0.99 means that >99% of bases for that taxon must be one allele; only recommended for low ploidy with <3 individuals
+    -a : use to specify the composite genome assembler 
     -s : use to specify the steps to skip: 1 skips making the composite genome; 2 also skips aligning reads to the composite reference; 3 also skips getting data for each site and mapping the composite genome to a known reference if available; 4 skips to identifying whether sites are variable among taxa given data for each site for each taxon
 
     Example command: ./sisrs -g 50000000 -r ./reference.fasta -p 40 -f fastq -m 4 -a test_data
@@ -58,13 +58,14 @@ LOCI=0
 WITHIN=0
 ALLELES=1
 DEBUG=0
+ASSEMBLER=Velvet
 
 if [[ $1 = "loci" ]]; then
     LOCI=1
     OPTIND=2 # tells getopts to start parsing at the second argument
 fi
 
-while getopts q:g:r:k:p:m:a:l:n:s:t:hd option
+while getopts q:g:r:k:p:m:a:f:l:n:s:t:hd option
 do
     case "${option}"
 	in
@@ -74,7 +75,8 @@ do
 	k) KMER=${OPTARG};;
 	p) PROCESSORS=${OPTARG};;
 	m) MISSING=${OPTARG};;
-	a) MAINFOLDER=${OPTARG};;
+	f) MAINFOLDER=${OPTARG};;
+        a) ASSEMBLER=${OPTARG};;
 	l) ALLELES=${OPTARG};;
 	n) MINREAD=${OPTARG};;
 	t) THRESHOLD=${OPTARG};;
@@ -93,8 +95,10 @@ DIRS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"    #where is the sisrs 
 DIR=$( dirname ${DIRS} )                                    #go one level up from location of sisrs file
 MAINFOLDER=$( echo "${MAINFOLDER}" | sed -e "s/\/*$//" )    #remove trailing / if necessary
 
-which velveth &>/dev/null
-[ $? -eq 0 ] || { echo "Velvet must be installed to run SISRS. The installation folder must be in your path. Aborting."; exit 1; }
+if [[ $ASSEMBLER -eq Velvet ]]; then
+    which velveth &>/dev/null
+    [ $? -eq 0 ] || { echo "Velvet must be installed to run SISRS. The installation folder must be in your path.    Aborting."; exit 1; }
+fi
 which bowtie2 &>/dev/null
 [ $? -eq 0 ] || { echo "Bowtie2 must be installed to run SISRS. The installation folder must be in your path. Aborting."; exit 1; }
 which parallel &>/dev/null
@@ -245,7 +249,7 @@ function runSISRS()
 
 function copyRefContigs()
 {
-    grep -oe "NODE[^/]*" "${MAINFOLDER}/alignment.nex" | uniq -c | sort -k1 -nr | awk '{print $2}' > "${MAINFOLDER}/loci.txt"
+    grep -oe "[A-Z]*_*[0-9]*_*len[^/]*" "${MAINFOLDER}/alignment.nex" | uniq -c | sort -k1 -nr | awk '{print $2}' > "${MAINFOLDER}/loci.txt"
     python ${DIR}/libexec/gfr/get_seq.py "${MAINFOLDER}/velvetoutput/contigs.fa" "${MAINFOLDER}/loci.txt" "${MAINFOLDER}/ref_genes.fa" 
 }
 
