added checks for errors

diff --git a/bin/sisrs b/bin/sisrs
--- a/bin/sisrs
+++ b/bin/sisrs
@@ -164,6 +164,11 @@ if [[ ${#FILELISTU[@]} -gt 0 ]]; then
 fi
 FOLDERLISTA=( $(echo "${FOLDERLISTU[@]} ${FOLDERLIST[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ') )
 
+if [[ ${#FOLDERLISTA[@]} -lt 1 ]]; then
+    echo "There were no data files"
+    exit 1
+fi
+
 if [ -z "$MISSING" ]; then MISSING=$((${#FOLDERLISTA[@]} - 2)); fi    #minimum of data for 2 species unless otherwise specified
 
 subSample(){
@@ -178,7 +183,12 @@ subSample(){
     DENOM=$((100*2*${#FOLDERLISTA[@]}))      #assumes 100bp reads - add option in future
     LEFTREADS=$((${NUMER}/${DENOM}))
     mkdir ${MAINFOLDER}/subsamples
-    parallel --jobs "${PROCESSORS}" "${DIR}/libexec/sisrs/sub_sample_for_velvet_unshuff.py ${LEFTREADS} {}" ::: "${FOLDERLISTA[@]}"   #subsample data and shuffle 
+    parallel --jobs "${PROCESSORS}" "${DIR}/libexec/sisrs/sub_sample_for_velvet_unshuff.py ${LEFTREADS} {}" ::: "${FOLDERLISTA[@]}"   #subsample data and shuffle
+    
+    if [[ $? != 0 ]]; then
+        echo "Subsampling failed"
+        exit 1
+    fi
 }
 
 buildContigs(){
@@ -268,12 +278,21 @@ identifyFixedSites(){
     samtools faidx ${MAINFOLDER}/${CONTIGS}/contigs.fa
     parallel --jobs "${PROCESSORS}" "samtools mpileup -f ${MAINFOLDER}/${CONTIGS}/contigs.fa" '$( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).bam -A > $( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).pileups' ::: "${FILELIST[@]}" "${FILELISTU[@]}"
     parallel --jobs "${PROCESSORS}" "${DIR}/libexec/sisrs/specific_genome.py {} ${MAINFOLDER}/${CONTIGS}/contigs.fa" ::: "${FOLDERLISTA[@]}"
+    
+    if [[ $? != 0 ]]; then
+        echo "specific_genome.py failed"
+        exit 1
+    fi
 
     parallel --jobs "${PROCESSORS}" "samtools faidx {}/contigs.fa" ::: "${FOLDERLISTA[@]}"
     parallel --jobs "${PROCESSORS}" 'samtools mpileup -f $(dirname {})/contigs.fa $( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).bam -A > $( echo {} | sed 's/R1//' | sed 's/\.[^.]*$//' ).pileups' ::: "${FILELIST[@]}" "${FILELISTU[@]}"
     
     #put base for each site in a dictionary (allows no variation when calling sites)
     parallel --jobs "${PROCESSORS}" "${DIR}/libexec/sisrs/get_pruned_dict.py {} ${MINREAD} ${THRESHOLD}" ::: "${FOLDERLISTA[@]}"
+    if [[ $? != 0 ]]; then
+        echo "get_pruned_dict.py failed"
+        exit 1
+    fi
     echo ==== Done Identifying Fixed Sites Without Error ====
 }
 
@@ -283,11 +302,20 @@ outputAlignment(){
     else
         ${DIR}/libexec/sisrs/get_alignment.py $((${#FOLDERLISTA[@]} - 2)) X ${MAINFOLDER} ${ASSEMBLER}       #alignment with up to all but 2 missing
     fi
+    if [[ $? != 0 ]]; then
+        echo "get_alignment.py failed"
+        exit 1
+    fi
+    
 }
 
 changeMissing(){
     if [[ ${MISSING} -lt $((${#FOLDERLISTA[@]} - 2)) ]]; then
         ${DIR}/libexec/sisrs/filter_nexus_for_missing.py ${MAINFOLDER}/alignment.nex ${MISSING}       #alignment w specified number missing
+    fi
+    if [[ $? != 0 ]]; then
+        echo "filtering for missing failed"
+        exit 1
     fi
 }
 
